### 해양수산부 국립해양조사원_연안 침수 정보 조회

이 데이터는 해양수산부 국립해양조사원에서 2009년~2020년까지 제작된 100년빈도 규모의 연안 인접지역 침수범위 예측정보를 제공하기 위해 수집한 데이터입니다.
검색 대상 시군구코드 등 값을 파라미터로 데이터를 조회할 수 있으며, 본 데이터의 주요 내용은 시도, 시군구명과 예측 침수값 및 침수시 공간정보 등 정보로 구성되어 있습니다.
본 데이터는 지방자치단체에서 침수 취약 지역의 방재 대책 수립 시 활용할 수 있으며, 재난관리 담당 부서가 안전 진단 및 예방 활동의 기초자료로 사용할 수 있습니다. 또한 침수 위험지구 관리와 연안 개발계획 수립 등 정책 수립 과정에서도 사용할 수 있습니다.

* 분류체계: 해양수산 - 해양수산·어촌
* 제공기관: 해양수산부 국립해양조사원
* 관리부서명:    해양예보과	관리부서 전화번호	051-400-4387
* API 유형:   REST	데이터포맷	JSON+XML
* End Point: https://apis.data.go.kr/1192136/waterlogged
* Service:  /GetWaterloggedApiService - 연안침수정보:우리나라 연안에 대한 조위별 침수 정보 제공 서비스

In [1]:
%useLatestDescriptors

%use dataframe
%use kandy

##### 시군구 코드 정보
* 출처 : https://www.data.go.kr/cmm/cmm/fileDownload.do?atchFileId=FILE_000000003661213&fileDetailSn=1
* <오픈API 활용가이드_연안 침수 정보> 내용중 [ 연안 침수 정보 대상 시군구 코드 ] 사용

In [2]:
val url_code = "/Users/unchil/Desktop/code.csv"
val df_code = DataFrame.readCsv(url_code, ',')
df_code.describe()

kotlin-logging: initializing... active logger factory: Slf4jLoggerFactory

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
시군구코드,Int,69,69,0,26110,1,40556.202899,9302.080009,26110,28716.666667,44825.000000,47460.333333,52800
시도명,String,69,10,0,전라남도,16,null,null,경기도,경상북도,인천광역시,전라남도,충청남도
시군구명,String,69,63,0,중구,3,null,null,강서구,남해군,서산시,중구,화성시

In [ ]:
val codeList = df_code.시군구코드.toList()

In [3]:
val serviceKeyFilePath = "/Users/unchil/AndroidStudioProjects/OceanWaterInfo/collectionServer/src/main/resources/application.json"
val configData = DataRow.readJson(path=serviceKeyFilePath)
val config = configData["WATER_LOGGED"]

In [5]:
val sggCd = codeList[0]
val url = "${config.endPoint}/${config.subPath}" +
        "?serviceKey=${config.apikey}&type=json&sggCd=${sggCd}&numOfRows=300"

In [6]:
val df_raw = DataFrame.readJson(url)
df_raw.describe()

In [ ]:
val numOfRows = 300

val allDataFrames = mutableListOf<DataFrame<*>>()

codeList.forEachIndexed{ index, it ->
    val baseUrl = "${config.endPoint}/${config.subPath}" +
            "?serviceKey=${config.apikey}&type=json&sggCd=${it}&numOfRows=${numOfRows}"

    val firstUrl = "${baseUrl}&pageNo=1"

    val df_first = DataFrame.readJson(firstUrl)
    val data = df_first["body"]["items"]["item"].first() as DataFrame<*>

    val totalCount = (df_first["body"]["totalCount"][0] as Number).toInt()
    val totalPages = ceil(totalCount.toDouble() / numOfRows).toInt()
    println("ssgNm:${it}, 시군구:${data[0][0]}/${data[0][1]}, 총 데이터 개수: $totalCount, 전체 페이지 수: $totalPages")

    val dataFrames = mutableListOf<DataFrame<*>>()

    dataFrames.add(data)

    for (page in 2..totalPages) {
        val url = "$baseUrl&pageNo=$page"
        val df_page = DataFrame.readJson(url)
        val data = df_page["body"]["items"]["item"].first() as DataFrame<*>
        dataFrames.add(data)
    }

    val df_SggAll = dataFrames.concat()

    allDataFrames.add(df_SggAll)

}

val df = allDataFrames.concat()

In [11]:
df.describe()

name,type,count,unique,nulls,top,freq,min,p25,median,p75,max
ctpvNm,String,61776,10,0,전라남도,22749,경기도,경상남도,전라남도,전라남도,충청남도
sggNm,String,61776,63,0,거제시,5036,강서구,군산시,신안군,창원시 마산합포구,화성시
flodVlCn,String,61776,8,0,0.5-1.0,15648,0.0-0.5,0.5-1.0,1.0-1.5,1.5-2.0,3.0
geom,String,61776,59479,0,MULTIPOLYGON(((126.69502880335551 34....,10,MULTIPOLYGON(((125.39590418233408 34....,MULTIPOLYGON(((126.51703223225793 34....,MULTIPOLYGON(((127.40676440071759 34....,MULTIPOLYGON(((128.48661652979268 34....,MULTIPOLYGON(((129.49101948828513 35....

In [19]:
val countsDf = df.groupBy { flodVlCn }
    .count()
    .sortByDesc("flodVlCn")

countsDf

flodVlCn,count
3.0,2337
2.5-3.0,7
2.0-3.0,6748
2.0-2.5,21
1.5-2.0,10769
1.0-1.5,14754
0.5-1.0,15648
0.0-0.5,11492