### 해양수산부 국립해양조사원_국가해양관측망 실측 파랑
*from 해양수산부 국립해양조사원*
>국가해양관측망(해양관측부이, 해양과학기지 등)에서 관측하는 파랑(파고, 파주기, 파향) 데이터를 제공 기능

- **제공기관:** 해양수산부 국립해양조사원
- **API 유형:** REST	데이터포맷	JSON+XML
- **End Point:** *https://apis.data.go.kr/1192136/noonWave*
- **Service:**  */GetNoonWaveApiService*  [ 파랑(파고, 파주기, 파향) 데이터 ]

In [1]:
//%useLatestDescriptors
%use dataframe

In [3]:
val filePath = "/Users/unchil/AndroidStudioProjects/OceanWaterInfo/KotlinNotebooks/data/wave_Observatory_list.csv"
val df_observatory = DataFrame.readCsv(filePath, ',')

In [4]:
df_observatory

code,name
DT_0039,왕돌초
DT_0042,교본초
IE_0060,이어도
IE_0061,신안가거초
IE_0062,옹진소청초
KG_0021,제주남부
KG_0024,대한해협
KG_0025,남해동부
KG_0028,제주해협
KG_0101,울릉도북동
KG_0102,울릉도북서
TW_0062,해운대해수욕장
TW_0069,대천해수욕장
TW_0075,중문해수욕장
TW_0079,상왕등도
TW_0080,우이도
TW_0081,생일도
TW_0088,감천항
TW_0089,경포대해수욕장
TW_0090,송정해수욕장

In [34]:
val serviceKeyFilePath = "/Users/unchil/.EnvDataCollector/envDataCollector.json"
val configData = DataRow.readJson(path=serviceKeyFilePath)

In [56]:
val endPoint = configData.WAVE_INFO.endPoint.toString()
val serviceKey = configData.WAVE_INFO.apikey.toString()
val subPath = configData.WAVE_INFO.subPath.toString()
val pageNo = "1"
val numOfRows = "300"
val type = "json"
val obsCode = "TW_0069"
val reqDate = "20261006"
val min = "5"

In [57]:
val url = "${endPoint}/${subPath}?serviceKey=${serviceKey}&pageNo=$pageNo&numOfRows=$numOfRows&type=$type&regDate=${reqDate}&min=$min&obsCode=$obsCode"

In [58]:
val df_waveInfo = DataFrame.readJson(url)
df_waveInfo

In [59]:
df_waveInfo.body.items.item.concat()

obsvtrNm,lot,lat,obsrvnDt,wvhgt,wvpd,wvdrct,maxWvhgt,maxWvpd
대천해수욕장,126.457802,36.274109,2026-10-06 00:00,0.600000,4.700000,263.000000,1.000000,3.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:05,0.700000,5.300000,241.000000,0.900000,8.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:10,0.800000,5.300000,250.000000,1.000000,8.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:15,0.700000,4.900000,263.000000,0.900000,6.500000
대천해수욕장,126.457802,36.274109,2026-10-06 00:20,0.600000,4.500000,341.000000,1.000000,5.500000
대천해수욕장,126.457802,36.274109,2026-10-06 00:25,0.600000,4.900000,290.000000,0.900000,4.500000
대천해수욕장,126.457802,36.274109,2026-10-06 00:30,0.700000,5.300000,252.000000,1.000000,7.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:35,0.600000,4.800000,297.000000,0.800000,6.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:40,0.700000,5.100000,258.000000,1.200000,5.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:45,0.700000,4.800000,278.000000,1.000000,5.500000
대천해수욕장,126.457802,36.274109,2026-10-06 00:50,0.700000,4.900000,213.000000,1.000000,6.000000
대천해수욕장,126.457802,36.274109,2026-10-06 00:55,0.600000,4.700000,353.000000,0.700000,4.500000
대천해수욕장,126.457802,36.274109,2026-10-06 01:00,0.600000,5.000000,272.000000,1.200000,5.500000
대천해수욕장,126.457802,36.274109,2026-10-06 01:05,0.700000,4.900000,331.000000,1.000000,5.000000
대천해수욕장,126.457802,36.274109,2026-10-06 01:10,0.700000,5.000000,336.000000,1.100000,5.000000
대천해수욕장,126.457802,36.274109,2026-10-06 01:15,0.600000,5.200000,244.000000,1.100000,6.000000
대천해수욕장,126.457802,36.274109,2026-10-06 01:20,0.600000,4.700000,270.000000,0.800000,3.500000
대천해수욕장,126.457802,36.274109,2026-10-06 01:25,0.600000,4.700000,342.000000,0.800000,6.500000
대천해수욕장,126.457802,36.274109,2026-10-06 01:30,0.600000,5.000000,342.000000,0.900000,5.500000
대천해수욕장,126.457802,36.274109,2026-10-06 01:35,0.600000,4.400000,255.000000,1.000000,6.000000